server:
  port: 8081
spring:
  datasource:
    url: "jdbc:oracle:thin:@//db:1521/orcl"
    username: system
    password: password
    driver-class-name: oracle.jdbc.OracleDriver
  jackson:
    serialization:
      fail-on-empty-beans: false
  jpa:
    database-platform: org.hibernate.dialect.Oracle12cDialect
    hibernate:
      ddl-auto: update
  application:
    name: eats-pagamento-service
  sleuth:
    sampler:
      percentage: 0.1
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://service-registry:8761/eureka
      
kafka:
  server:
    url: http://kafka:9092
  topics:
    pedido:
      confirma:
        pagamento: topic.pedido.confirma.pagamento
